package com.dc.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dc.greendao.TopMovieCache;
import com.dc.greendao.NorthAmericaCache;

import com.dc.greendao.TopMovieCacheDao;
import com.dc.greendao.NorthAmericaCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topMovieCacheDaoConfig;
    private final DaoConfig northAmericaCacheDaoConfig;

    private final TopMovieCacheDao topMovieCacheDao;
    private final NorthAmericaCacheDao northAmericaCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topMovieCacheDaoConfig = daoConfigMap.get(TopMovieCacheDao.class).clone();
        topMovieCacheDaoConfig.initIdentityScope(type);

        northAmericaCacheDaoConfig = daoConfigMap.get(NorthAmericaCacheDao.class).clone();
        northAmericaCacheDaoConfig.initIdentityScope(type);

        topMovieCacheDao = new TopMovieCacheDao(topMovieCacheDaoConfig, this);
        northAmericaCacheDao = new NorthAmericaCacheDao(northAmericaCacheDaoConfig, this);

        registerDao(TopMovieCache.class, topMovieCacheDao);
        registerDao(NorthAmericaCache.class, northAmericaCacheDao);
    }
    
    public void clear() {
        topMovieCacheDaoConfig.getIdentityScope().clear();
        northAmericaCacheDaoConfig.getIdentityScope().clear();
    }

    public TopMovieCacheDao getTopMovieCacheDao() {
        return topMovieCacheDao;
    }

    public NorthAmericaCacheDao getNorthAmericaCacheDao() {
        return northAmericaCacheDao;
    }

}
